nome_do_paciente = (input("Escreva seu nome: "))
alt_paciente = float (input("Digite sua altura: "))
peso_paciente =  float (input("Digite seu peso: "))
imc = peso_paciente / (alt_paciente **2)
print(f"Bem vindo ao Unesc saúde", f"{nome_do_paciente}!", f"seu IMC é: {imc:.2f}")